yoyoran/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('yoyozj.urls', namespace="yoyozj")),
    url(r'^admin/', admin.site.urls),
]

yoyozj/urls.py
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import index, fresh_food


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^fresh_food/$', fresh_food, name='fresh_food'),
]

yoyozj/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class ArticleManager(models.Manager):
    def query_by_column(self, column_id):
        query = self.get_queryset().filter(column_id=column_id)
        return query

    def query_by_user(self, user_id):
        user = User.objects.get(id=user_id)
        article_list = user.article_set.all()
        return article_list

    def query_by_polls(self):
        query = self.get_queryset().order_by('poll_num')
        return query

    def query_by_time(self):
        query = self.get_queryset().order_by('-pub_date')
        return query

    def query_by_keyword(self, keyword):
        query = self.get_queryset().filter(title__contains=keyword)
        return query


@python_2_unicode_compatible
class NewUser(AbstractUser):
    profile = models.CharField('profile', default='', max_length=256)

    def __str__(self):
        return self.username


@python_2_unicode_compatible
class Column(models.Model):
    name = models.CharField('column_name', max_length=256)
    intro = models.TextField('introduction', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'column'
        verbose_name_plural = 'column'
        ordering = ['name']


@python_2_unicode_compatible
class Article(models.Model):
    column = models.ForeignKey(Column, blank=True, null=True, verbose_name='belong to')
    title = models.CharField(max_length=256)
    author = models.ForeignKey('Author')
    user = models.ManyToManyField('NewUser', blank=True)
    content = models.TextField('content')
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)
    update_time = models.DateTimeField(auto_now=True, null=True)
    published = models.BooleanField('notDraft', default=True)
    poll_num = models.IntegerField(default=0)
    comment_num = models.IntegerField(default=0)
    keep_num = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'article'

    objects = ArticleManager()


@python_2_unicode_compatible
class Comment(models.Model):
    user = models.ForeignKey('NewUser', null=True)
    article = models.ForeignKey(Article, null=True)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)
    poll_num = models.IntegerField(default=0)

    def __str__(self):
        return self.content


class Author(models.Model):
    name = models.CharField(max_length=256)
    profile = models.CharField('profile', default='', max_length=256)
    password = models.CharField('password', max_length=256)
    register_date = models.DateTimeField(auto_now_add=True, editable=True)

    def __str__(self):
        return self.name


class Poll(models.Model):
    user = models.ForeignKey('NewUser', null=True)
    article = models.ForeignKey(Article, null=True)
    comment = models.ForeignKey(Comment, null=True)

yoyozj/views.py
from django.shortcuts import render, HttpResponse
from yoyozj.models import Article, ArticleManager

# Create your views here.

def index(request):
    context = {
        'active_menu': 'homepage'
    }
    return render(request, 'yoyozj/index.html', context)
    # return HttpResponse('欢迎来到悠悠然网站')

def fresh_food(request):

    fresh_food_list = Article.objects.all()

    print(fresh_food_list)
    # print(ArticleManager.query_by_column())

    context = {
        'fresh_food_list': fresh_food_list,
        'active_menu': 'freshfood',
    }
    return render(request, 'yoyozj/freshfood.html', context)

yoyozj/templates/yoyozj/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!-- Template by Quackit.com -->
<!-- Images by various sources under the Creative Commons CC0 license and/or the Creative Commons Zero license. 
Although you can use them, for a more unique website, replace these images with your own. -->
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
{#    <link href="css/bootstrap.min.css" rel="stylesheet">#}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
{#    <link href="css/custom.css" rel="stylesheet">#}
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                	<span class="glyphicon glyphicon-fire"></span>
                    悠悠然
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li id="index">
                        <a href="{% url 'yoyozj:index' %}">首页</a>
                    </li>
                    <li id="freshfood">
                        <a href="{% url 'yoyozj:fresh_food' %}">友家生鲜</a>
                    </li>
                    <li>
                        <a href="#">湛江风俗</a>
                    </li>
                    <li>
                        <a href="#">湛江特产</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

    {% block content %}{% endblock %}



	<!-- Footer -->
    <footer class="page-footer">
    
    	<!-- Contact Us -->
        <div class="contact">
        	<div class="container">
				<h2 class="section-heading">Contact Us</h2>
				<p><span class="glyphicon glyphicon-earphone"></span><br> +1(23) 456 7890</p>
				<p><span class="glyphicon glyphicon-envelope"></span><br> info@example.com</p>
        	</div>
        </div>
        	
        <!-- Copyright etc -->
        <div class="small-print">
        	<div class="container">
        		<p>Copyright &copy; Example.com 2015</p>
        	</div>
        </div>
        
    </footer>

    <!-- jQuery -->
{#    <script src="js/jquery-1.11.3.min.js"></script>#}
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
{#    <script src="js/bootstrap.min.js"></script>#}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
{#    <script src="js/jquery.easing.min.js"></script>#}
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>

    <!-- Custom Javascript -->
{#    <script src="js/custom.js"></script>#}
    <script src="{% static 'js/custom.js' %}"></script>

    <script type="text/javascript">
        $('#{{active_menu}}').addClass("active");
    </script>

</body>

</html>

yoyozj/templates/yoyozj/freshfood.html
{% extends 'yoyozj/base.html' %}
{% load staticfiles %}

{% block title %}友家生鲜{% endblock %}

{% block content %}
    <link href="{% static 'css/fresh_food.css' %}" rel="stylesheet">
    <!-- Content -->
    <div class="container seafood-content">

        <!-- Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">友家海鲜
                    <small>新鲜食材</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            {% for fresh in fresh_food_list %}
                <div class="col-md-6 portfolio-item">
                    <a href="#">
                        <img class="img-responsive" src="{% static 'images/bridge.jpg' %}" alt="">
                    </a>
                    <h3>
                        <a href="#">{{ fresh.title }}</a>
                    </h3>
                    <p class="line-limit-length">{{ fresh.content }}</p>
                </div>
            {% endfor %}
            {#                <div class="col-md-6 portfolio-item">#}
            {#                    <a href="#">#}
            {#                        <img class="img-responsive" src="{% static 'images/timg2.jpg' %}" alt="">#}
            {#                    </a>#}
            {#                    <h3>#}
            {#                        <a href="#">{{ fresh.title }}</a>#}
            {#                    </h3>#}
            {#                    <p class="line-limit-length">{{ fresh.content }}</p>#}
            {#                </div>#}
        </div>
        <!-- /.row -->


        {#            <!-- Projects Row -->#}
        {#            <div class="row">#}
        {#                <div class="col-md-6 portfolio-item">#}
        {#                    <a href="#">#}
        {#                        <img class="img-responsive" src="{% static 'images/timg2.jpg' %}" alt="">#}
        {#                    </a>#}
        {#                    <h3>#}
        {#                        <a href="#">Project Title</a>#}
        {#                    </h3>#}
        {#                    <p>Upon yielding, kind sea subdue very seed sixth them lesser one lesser there earth days were#}
        {#                        multiply so sixth gathering fifth that man fowl made.</p>#}
        {#                </div>#}
        {#                <div class="col-md-6 portfolio-item">#}
        {#                    <a href="#">#}
        {#                        <img class="img-responsive" src="{% static 'images/timg3.jpg' %}" alt="">#}
        {#                    </a>#}
        {#                    <h3>#}
        {#                        <a href="#">Project Title</a>#}
        {#                    </h3>#}
        {#                    <p>Upon yielding, kind sea subdue very seed sixth them lesser one lesser there earth days were#}
        {#                        multiply so sixth gathering fifth that man fowl made.</p>#}
        {#                </div>#}
        {#            </div>#}
        {##}
        {##}
        {#            <!-- Projects Row -->#}
        {#            <div class="row">#}
        {#                <div class="col-md-6 portfolio-item">#}
        {#                    <a href="#">#}
        {#                        <img class="img-responsive" src="{% static 'images/timg4.jpg' %}" alt="">#}
        {#                    </a>#}
        {#                    <h3>#}
        {#                        <a href="#">Project Title</a>#}
        {#                    </h3>#}
        {#                    <p>Upon yielding, kind sea subdue very seed sixth them lesser one lesser there earth days were#}
        {#                        multiply so sixth gathering fifth that man fowl made.</p>#}
        {#                </div>#}
        {#                <div class="col-md-6 portfolio-item">#}
        {#                    <a href="#">#}
        {#                        <img class="img-responsive" src="{% static 'images/timg5.jpg' %}" alt="">#}
        {#                    </a>#}
        {#                    <h3>#}
        {#                        <a href="#">Project Title</a>#}
        {#                    </h3>#}
        {#                    <p>Upon yielding, kind sea subdue very seed sixth them lesser one lesser there earth days were#}
        {#                        multiply so sixth gathering fifth that man fowl made.</p>#}
        {#                </div>#}
        {#            </div>#}


        <!-- Pagination -->
        {#        <div class="row text-center">#}
        {#            <div class="col-lg-12">#}
        {#                <ul class="pagination">#}
        {#                    <li>#}
        {#                        <a href="#">&laquo;</a>#}
        {#                    </li>#}
        {#                    <li class="active">#}
        {#                        <a href="#">1</a>#}
        {#                    </li>#}
        {#                    <li>#}
        {#                        <a href="#">2</a>#}
        {#                    </li>#}
        {#                    <li>#}
        {#                        <a href="#">3</a>#}
        {#                    </li>#}
        {#                    <li>#}
        {#                        <a href="#">4</a>#}
        {#                    </li>#}
        {#                    <li>#}
        {#                        <a href="#">5</a>#}
        {#                    </li>#}
        {#                    <li>#}
        {#                        <a href="#">&raquo;</a>#}
        {#                    </li>#}
        {#                </ul>#}
        {#            </div>#}
        {#        </div>#}
        <!-- /.row -->


    </div>
    <!-- /.container -->
{% endblock %}

yoyozj/templates/yoyozj/index.html
{% extends "yoyozj/base.html" %}
{% load staticfiles %}

{% block content %}
    <!-- Header -->
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h3>采菊东篱下 悠然见南山</h3>
                <p>山气日夕佳 飞鸟相与还</p>
{#                <p>Objectively innovate empowered manufactured products whereas parallel platforms.</p>#}
                <a href="#" class="btn btn-primary btn-lg">Engage Now</a>
            </div>
        </div>
    </header>

	<!-- Intro Section -->
    <section class="intro">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                	<span class="glyphicon glyphicon-apple" style="font-size: 60px"></span>
                    <h2 class="section-heading">Completely synergize resource taxing relationships</h2>
                    <p class="text-light">Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                </div>
            </div>
        </div>
    </section>

	<!-- Content 1 -->
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img class="img-responsive img-circle center-block" src="{% static 'images/microphone.jpg' %}" alt="">
                </div>
                <div class="col-sm-6">
                	<h2 class="section-header">Best in Class</h2>
                	<p class="lead text-muted">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                	<a href="#" class="btn btn-primary btn-lg">Classify It</a>
                </div>

            </div>
        </div>
    </section>

	<!-- Content 2 -->
     <section class="content content-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                	<h2 class="section-header">Superior Quality</h2>
                	<p class="lead text-light">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                	<a href="#" class="btn btn-default btn-lg">Test It</a>
                </div>
                <div class="col-sm-6">
                    <img class="img-responsive img-circle center-block" src="{% static 'images/iphone.jpg' %}" alt="">
                </div>

            </div>
        </div>
    </section>

    <!-- Promos -->
	<div class="container-fluid">
        <div class="row promo">
        	<a href="#">
				<div class="col-md-4 promo-item item-1">
					<h3>
						Unleash
					</h3>
				</div>
            </a>
            <a href="#">
				<div class="col-md-4 promo-item item-2">
					<h3>
						Synergize
					</h3>
				</div>
            </a>

			<a href="#">
				<div class="col-md-4 promo-item item-3">
					<h3>
						Procrastinate
					</h3>
				</div>
            </a>
        </div>
    </div><!-- /.container-fluid -->

	<!-- Content 3 -->
     <section class="content content-3">
        <div class="container">
			<h2 class="section-header"><span class="glyphicon glyphicon-pushpin text-primary"></span><br> Sanity Check</h2>
			<p class="lead text-muted">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                    <a href="#" class="btn btn-primary btn-lg">Check Now</a>
            </div>
        </div>
    </section>
{% endblock %}